import Link from 'next/link'
import Head from 'next/head'

const Nos = () => {
  return (
    <div>
        <Head>
            <title>GuitarLA - Nos</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Nos</h1>
        <Link href='/'>To inicio</Link>
    </div>
  )
}

export default Nos